spring:
  cloud:
    config:
      server:
        git:
          uri: http://192.168.0.111/yoogurt/config-server.git
          search-paths: resources
          default-label: master
          username: root
          password: taxi123456