server:
  port: 9998
spring:
  application:
    name: config-server
encrypt:
  key: Yoogurt-Taxi123~!@#
security:
  user:
    password: taxi123456
    name: yoogurt
---
spring:
  profiles:
    active: github